# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(893, 633)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 20, 871, 491))
        self.widget.setObjectName("widget")
        self.submit = QtWidgets.QPushButton(self.widget)
        self.submit.setGeometry(QtCore.QRect(170, 450, 181, 28))
        self.submit.setStyleSheet("")
        self.submit.setObjectName("submit")
        self.question = QtWidgets.QLabel(self.widget)
        self.question.setGeometry(QtCore.QRect(100, 20, 701, 71))
        self.question.setStyleSheet("")
        self.question.setObjectName("question")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 140, 311, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.option_a = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.option_a.setObjectName("option_a")
        self.verticalLayout.addWidget(self.option_a)
        self.option_b = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.option_b.setObjectName("option_b")
        self.verticalLayout.addWidget(self.option_b)
        self.option_c = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.option_c.setObjectName("option_c")
        self.verticalLayout.addWidget(self.option_c)
        self.option_d = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.option_d.setObjectName("option_d")
        self.verticalLayout.addWidget(self.option_d)
        self.option_e = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.option_e.setEnabled(True)
        self.option_e.setCheckable(True)
        self.option_e.setChecked(False)
        self.option_e.setObjectName("option_e")
        self.verticalLayout.addWidget(self.option_e)
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(440, 100, 361, 331))
        self.frame.setStyleSheet("QFrame{\n"
"border-radius:15px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.id_text = QtWidgets.QLabel(self.widget)
        self.id_text.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.id_text.setText("")
        self.id_text.setObjectName("id_text")
        self.sign_in = QtWidgets.QPushButton(self.centralwidget)
        self.sign_in.setGeometry(QtCore.QRect(210, 550, 151, 31))
        self.sign_in.setStyleSheet("")
        self.sign_in.setObjectName("sign_in")
        self.info = QtWidgets.QLabel(self.centralwidget)
        self.info.setGeometry(QtCore.QRect(570, 540, 311, 51))
        self.info.setObjectName("info")
        self.enter_id = QtWidgets.QLineEdit(self.centralwidget)
        self.enter_id.setGeometry(QtCore.QRect(40, 550, 161, 31))
        self.enter_id.setObjectName("enter_id")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 893, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.submit.setText(_translate("MainWindow", "GÖNDER"))
        self.question.setText(_translate("MainWindow", "SORU"))
        self.option_a.setText(_translate("MainWindow", "A"))
        self.option_b.setText(_translate("MainWindow", "B"))
        self.option_c.setText(_translate("MainWindow", "C"))
        self.option_d.setText(_translate("MainWindow", "D"))
        self.option_e.setText(_translate("MainWindow", "E"))
        self.sign_in.setText(_translate("MainWindow", "GİRİŞ"))
        self.info.setText(_translate("MainWindow", "BİLGİ:"))
